sudo: false

rvm:
  - "2.2.5"
  - "2.3.1"

before_script:
  - cp config/sp-gestion.sample.yml config/sp-gestion.yml
  - bundle exec rake db:create db:migrate

bundler_args:
  --without development staging production

services:
  - memcached

script:
  - bundle exec rake spec

notifications:
  disabled: true

env:
  global:
    - RAILS_ENV=test
